// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.2
// source: proto/avatar.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "avatar";

export enum Head {
  HEAD_UNSPECIFIED = 0,
  HEAD_AFRO = 1,
  HEAD_BALD = 2,
  HEAD_BANGS = 3,
  HEAD_BANGS_TWO = 4,
  HEAD_BANTU_KNOTS = 5,
  HEAD_BEANIE = 6,
  HEAD_BEAR = 7,
  HEAD_BUN = 8,
  HEAD_BUN_CLIP = 9,
  HEAD_BUN_KNOTS = 10,
  HEAD_BUN_TWO = 11,
  HEAD_COLOR_BUN = 12,
  HEAD_COLOR_MEDIUM = 13,
  HEAD_CORNROWS = 14,
  HEAD_CORNROWS_LIGHT = 15,
  HEAD_DOC_ONE = 16,
  HEAD_DOC_THREE = 17,
  HEAD_DOC_TWO = 18,
  HEAD_DREADS_ONE = 19,
  HEAD_DREADS_TWO = 20,
  HEAD_FLAT_TOP = 21,
  HEAD_FLAT_TOP_LONG = 22,
  HEAD_GRAY_SHORT = 23,
  HEAD_HAT_HIP = 24,
  HEAD_HIJAB = 25,
  HEAD_LONG_AFRO = 26,
  HEAD_LONG_BANGS = 27,
  HEAD_LONG_CURLY = 28,
  HEAD_LONG_HAIR = 29,
  HEAD_MEDIUM_BANGS = 30,
  HEAD_MEDIUM_BANGS_COLOR = 31,
  HEAD_MEDIUM_BANGS_ONE = 32,
  HEAD_MEDIUM_ONE = 33,
  HEAD_MEDIUM_STRAIGHT = 34,
  HEAD_MEDIUM_THREE = 35,
  HEAD_MEDIUM_TWO = 36,
  HEAD_MOHAWK = 37,
  HEAD_MOHAWK_KNOTS = 38,
  HEAD_NO_HAIR_THREE = 39,
  HEAD_NO_HAIR_TWO = 40,
  HEAD_POMP = 41,
  HEAD_SHAVED = 42,
  HEAD_SHAVED_ONE = 43,
  HEAD_SHAVED_THREE = 44,
  HEAD_SHORT_FIVE = 45,
  HEAD_SHORT_FOUR = 46,
  HEAD_SHORT_ONE = 47,
  HEAD_SHORT_THREE = 48,
  HEAD_SHORT_TWO = 49,
  HEAD_TURBAN = 50,
  HEAD_TWISTS = 51,
  HEAD_TWISTS_TWO = 52,
  HEAD_WAVY = 53,
  UNRECOGNIZED = -1,
}

export function headFromJSON(object: any): Head {
  switch (object) {
    case 0:
    case "HEAD_UNSPECIFIED":
      return Head.HEAD_UNSPECIFIED;
    case 1:
    case "HEAD_AFRO":
      return Head.HEAD_AFRO;
    case 2:
    case "HEAD_BALD":
      return Head.HEAD_BALD;
    case 3:
    case "HEAD_BANGS":
      return Head.HEAD_BANGS;
    case 4:
    case "HEAD_BANGS_TWO":
      return Head.HEAD_BANGS_TWO;
    case 5:
    case "HEAD_BANTU_KNOTS":
      return Head.HEAD_BANTU_KNOTS;
    case 6:
    case "HEAD_BEANIE":
      return Head.HEAD_BEANIE;
    case 7:
    case "HEAD_BEAR":
      return Head.HEAD_BEAR;
    case 8:
    case "HEAD_BUN":
      return Head.HEAD_BUN;
    case 9:
    case "HEAD_BUN_CLIP":
      return Head.HEAD_BUN_CLIP;
    case 10:
    case "HEAD_BUN_KNOTS":
      return Head.HEAD_BUN_KNOTS;
    case 11:
    case "HEAD_BUN_TWO":
      return Head.HEAD_BUN_TWO;
    case 12:
    case "HEAD_COLOR_BUN":
      return Head.HEAD_COLOR_BUN;
    case 13:
    case "HEAD_COLOR_MEDIUM":
      return Head.HEAD_COLOR_MEDIUM;
    case 14:
    case "HEAD_CORNROWS":
      return Head.HEAD_CORNROWS;
    case 15:
    case "HEAD_CORNROWS_LIGHT":
      return Head.HEAD_CORNROWS_LIGHT;
    case 16:
    case "HEAD_DOC_ONE":
      return Head.HEAD_DOC_ONE;
    case 17:
    case "HEAD_DOC_THREE":
      return Head.HEAD_DOC_THREE;
    case 18:
    case "HEAD_DOC_TWO":
      return Head.HEAD_DOC_TWO;
    case 19:
    case "HEAD_DREADS_ONE":
      return Head.HEAD_DREADS_ONE;
    case 20:
    case "HEAD_DREADS_TWO":
      return Head.HEAD_DREADS_TWO;
    case 21:
    case "HEAD_FLAT_TOP":
      return Head.HEAD_FLAT_TOP;
    case 22:
    case "HEAD_FLAT_TOP_LONG":
      return Head.HEAD_FLAT_TOP_LONG;
    case 23:
    case "HEAD_GRAY_SHORT":
      return Head.HEAD_GRAY_SHORT;
    case 24:
    case "HEAD_HAT_HIP":
      return Head.HEAD_HAT_HIP;
    case 25:
    case "HEAD_HIJAB":
      return Head.HEAD_HIJAB;
    case 26:
    case "HEAD_LONG_AFRO":
      return Head.HEAD_LONG_AFRO;
    case 27:
    case "HEAD_LONG_BANGS":
      return Head.HEAD_LONG_BANGS;
    case 28:
    case "HEAD_LONG_CURLY":
      return Head.HEAD_LONG_CURLY;
    case 29:
    case "HEAD_LONG_HAIR":
      return Head.HEAD_LONG_HAIR;
    case 30:
    case "HEAD_MEDIUM_BANGS":
      return Head.HEAD_MEDIUM_BANGS;
    case 31:
    case "HEAD_MEDIUM_BANGS_COLOR":
      return Head.HEAD_MEDIUM_BANGS_COLOR;
    case 32:
    case "HEAD_MEDIUM_BANGS_ONE":
      return Head.HEAD_MEDIUM_BANGS_ONE;
    case 33:
    case "HEAD_MEDIUM_ONE":
      return Head.HEAD_MEDIUM_ONE;
    case 34:
    case "HEAD_MEDIUM_STRAIGHT":
      return Head.HEAD_MEDIUM_STRAIGHT;
    case 35:
    case "HEAD_MEDIUM_THREE":
      return Head.HEAD_MEDIUM_THREE;
    case 36:
    case "HEAD_MEDIUM_TWO":
      return Head.HEAD_MEDIUM_TWO;
    case 37:
    case "HEAD_MOHAWK":
      return Head.HEAD_MOHAWK;
    case 38:
    case "HEAD_MOHAWK_KNOTS":
      return Head.HEAD_MOHAWK_KNOTS;
    case 39:
    case "HEAD_NO_HAIR_THREE":
      return Head.HEAD_NO_HAIR_THREE;
    case 40:
    case "HEAD_NO_HAIR_TWO":
      return Head.HEAD_NO_HAIR_TWO;
    case 41:
    case "HEAD_POMP":
      return Head.HEAD_POMP;
    case 42:
    case "HEAD_SHAVED":
      return Head.HEAD_SHAVED;
    case 43:
    case "HEAD_SHAVED_ONE":
      return Head.HEAD_SHAVED_ONE;
    case 44:
    case "HEAD_SHAVED_THREE":
      return Head.HEAD_SHAVED_THREE;
    case 45:
    case "HEAD_SHORT_FIVE":
      return Head.HEAD_SHORT_FIVE;
    case 46:
    case "HEAD_SHORT_FOUR":
      return Head.HEAD_SHORT_FOUR;
    case 47:
    case "HEAD_SHORT_ONE":
      return Head.HEAD_SHORT_ONE;
    case 48:
    case "HEAD_SHORT_THREE":
      return Head.HEAD_SHORT_THREE;
    case 49:
    case "HEAD_SHORT_TWO":
      return Head.HEAD_SHORT_TWO;
    case 50:
    case "HEAD_TURBAN":
      return Head.HEAD_TURBAN;
    case 51:
    case "HEAD_TWISTS":
      return Head.HEAD_TWISTS;
    case 52:
    case "HEAD_TWISTS_TWO":
      return Head.HEAD_TWISTS_TWO;
    case 53:
    case "HEAD_WAVY":
      return Head.HEAD_WAVY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Head.UNRECOGNIZED;
  }
}

export function headToJSON(object: Head): string {
  switch (object) {
    case Head.HEAD_UNSPECIFIED:
      return "HEAD_UNSPECIFIED";
    case Head.HEAD_AFRO:
      return "HEAD_AFRO";
    case Head.HEAD_BALD:
      return "HEAD_BALD";
    case Head.HEAD_BANGS:
      return "HEAD_BANGS";
    case Head.HEAD_BANGS_TWO:
      return "HEAD_BANGS_TWO";
    case Head.HEAD_BANTU_KNOTS:
      return "HEAD_BANTU_KNOTS";
    case Head.HEAD_BEANIE:
      return "HEAD_BEANIE";
    case Head.HEAD_BEAR:
      return "HEAD_BEAR";
    case Head.HEAD_BUN:
      return "HEAD_BUN";
    case Head.HEAD_BUN_CLIP:
      return "HEAD_BUN_CLIP";
    case Head.HEAD_BUN_KNOTS:
      return "HEAD_BUN_KNOTS";
    case Head.HEAD_BUN_TWO:
      return "HEAD_BUN_TWO";
    case Head.HEAD_COLOR_BUN:
      return "HEAD_COLOR_BUN";
    case Head.HEAD_COLOR_MEDIUM:
      return "HEAD_COLOR_MEDIUM";
    case Head.HEAD_CORNROWS:
      return "HEAD_CORNROWS";
    case Head.HEAD_CORNROWS_LIGHT:
      return "HEAD_CORNROWS_LIGHT";
    case Head.HEAD_DOC_ONE:
      return "HEAD_DOC_ONE";
    case Head.HEAD_DOC_THREE:
      return "HEAD_DOC_THREE";
    case Head.HEAD_DOC_TWO:
      return "HEAD_DOC_TWO";
    case Head.HEAD_DREADS_ONE:
      return "HEAD_DREADS_ONE";
    case Head.HEAD_DREADS_TWO:
      return "HEAD_DREADS_TWO";
    case Head.HEAD_FLAT_TOP:
      return "HEAD_FLAT_TOP";
    case Head.HEAD_FLAT_TOP_LONG:
      return "HEAD_FLAT_TOP_LONG";
    case Head.HEAD_GRAY_SHORT:
      return "HEAD_GRAY_SHORT";
    case Head.HEAD_HAT_HIP:
      return "HEAD_HAT_HIP";
    case Head.HEAD_HIJAB:
      return "HEAD_HIJAB";
    case Head.HEAD_LONG_AFRO:
      return "HEAD_LONG_AFRO";
    case Head.HEAD_LONG_BANGS:
      return "HEAD_LONG_BANGS";
    case Head.HEAD_LONG_CURLY:
      return "HEAD_LONG_CURLY";
    case Head.HEAD_LONG_HAIR:
      return "HEAD_LONG_HAIR";
    case Head.HEAD_MEDIUM_BANGS:
      return "HEAD_MEDIUM_BANGS";
    case Head.HEAD_MEDIUM_BANGS_COLOR:
      return "HEAD_MEDIUM_BANGS_COLOR";
    case Head.HEAD_MEDIUM_BANGS_ONE:
      return "HEAD_MEDIUM_BANGS_ONE";
    case Head.HEAD_MEDIUM_ONE:
      return "HEAD_MEDIUM_ONE";
    case Head.HEAD_MEDIUM_STRAIGHT:
      return "HEAD_MEDIUM_STRAIGHT";
    case Head.HEAD_MEDIUM_THREE:
      return "HEAD_MEDIUM_THREE";
    case Head.HEAD_MEDIUM_TWO:
      return "HEAD_MEDIUM_TWO";
    case Head.HEAD_MOHAWK:
      return "HEAD_MOHAWK";
    case Head.HEAD_MOHAWK_KNOTS:
      return "HEAD_MOHAWK_KNOTS";
    case Head.HEAD_NO_HAIR_THREE:
      return "HEAD_NO_HAIR_THREE";
    case Head.HEAD_NO_HAIR_TWO:
      return "HEAD_NO_HAIR_TWO";
    case Head.HEAD_POMP:
      return "HEAD_POMP";
    case Head.HEAD_SHAVED:
      return "HEAD_SHAVED";
    case Head.HEAD_SHAVED_ONE:
      return "HEAD_SHAVED_ONE";
    case Head.HEAD_SHAVED_THREE:
      return "HEAD_SHAVED_THREE";
    case Head.HEAD_SHORT_FIVE:
      return "HEAD_SHORT_FIVE";
    case Head.HEAD_SHORT_FOUR:
      return "HEAD_SHORT_FOUR";
    case Head.HEAD_SHORT_ONE:
      return "HEAD_SHORT_ONE";
    case Head.HEAD_SHORT_THREE:
      return "HEAD_SHORT_THREE";
    case Head.HEAD_SHORT_TWO:
      return "HEAD_SHORT_TWO";
    case Head.HEAD_TURBAN:
      return "HEAD_TURBAN";
    case Head.HEAD_TWISTS:
      return "HEAD_TWISTS";
    case Head.HEAD_TWISTS_TWO:
      return "HEAD_TWISTS_TWO";
    case Head.HEAD_WAVY:
      return "HEAD_WAVY";
    case Head.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Face {
  FACE_UNSPECIFIED = 0,
  FACE_ANGRY = 1,
  FACE_ANGRY_FANG = 2,
  FACE_AWE = 3,
  FACE_BIG_SMILE = 4,
  FACE_BLANK = 5,
  FACE_CALM = 6,
  FACE_CALM_WITH_MASK = 7,
  FACE_CHEEKY = 8,
  FACE_CHEERS_WITH_MASK = 9,
  FACE_CONCERNED = 10,
  FACE_CONCERNED_FEAR = 11,
  FACE_CONTEMPT = 12,
  FACE_CUTE = 13,
  FACE_CYCLOPS = 14,
  FACE_DRIVEN = 15,
  FACE_EATING_HAPPY = 16,
  FACE_EXPLAINING = 17,
  FACE_EYES_CLOSED = 18,
  FACE_FEAR = 19,
  FACE_HECTIC = 20,
  FACE_LOVE_GRIN_TEETH = 21,
  FACE_LOVE_GRIN_TONGUE = 22,
  FACE_MONSTER = 23,
  FACE_OLD = 24,
  FACE_RAGE = 25,
  FACE_SERIOUS = 26,
  FACE_SMILE = 27,
  FACE_SMILE_LOL = 28,
  FACE_SMILE_TEETH = 29,
  FACE_SMILE_WITH_MASK = 30,
  FACE_SOLEMN = 31,
  FACE_SUSPICIOUS = 32,
  FACE_TIRED = 33,
  UNRECOGNIZED = -1,
}

export function faceFromJSON(object: any): Face {
  switch (object) {
    case 0:
    case "FACE_UNSPECIFIED":
      return Face.FACE_UNSPECIFIED;
    case 1:
    case "FACE_ANGRY":
      return Face.FACE_ANGRY;
    case 2:
    case "FACE_ANGRY_FANG":
      return Face.FACE_ANGRY_FANG;
    case 3:
    case "FACE_AWE":
      return Face.FACE_AWE;
    case 4:
    case "FACE_BIG_SMILE":
      return Face.FACE_BIG_SMILE;
    case 5:
    case "FACE_BLANK":
      return Face.FACE_BLANK;
    case 6:
    case "FACE_CALM":
      return Face.FACE_CALM;
    case 7:
    case "FACE_CALM_WITH_MASK":
      return Face.FACE_CALM_WITH_MASK;
    case 8:
    case "FACE_CHEEKY":
      return Face.FACE_CHEEKY;
    case 9:
    case "FACE_CHEERS_WITH_MASK":
      return Face.FACE_CHEERS_WITH_MASK;
    case 10:
    case "FACE_CONCERNED":
      return Face.FACE_CONCERNED;
    case 11:
    case "FACE_CONCERNED_FEAR":
      return Face.FACE_CONCERNED_FEAR;
    case 12:
    case "FACE_CONTEMPT":
      return Face.FACE_CONTEMPT;
    case 13:
    case "FACE_CUTE":
      return Face.FACE_CUTE;
    case 14:
    case "FACE_CYCLOPS":
      return Face.FACE_CYCLOPS;
    case 15:
    case "FACE_DRIVEN":
      return Face.FACE_DRIVEN;
    case 16:
    case "FACE_EATING_HAPPY":
      return Face.FACE_EATING_HAPPY;
    case 17:
    case "FACE_EXPLAINING":
      return Face.FACE_EXPLAINING;
    case 18:
    case "FACE_EYES_CLOSED":
      return Face.FACE_EYES_CLOSED;
    case 19:
    case "FACE_FEAR":
      return Face.FACE_FEAR;
    case 20:
    case "FACE_HECTIC":
      return Face.FACE_HECTIC;
    case 21:
    case "FACE_LOVE_GRIN_TEETH":
      return Face.FACE_LOVE_GRIN_TEETH;
    case 22:
    case "FACE_LOVE_GRIN_TONGUE":
      return Face.FACE_LOVE_GRIN_TONGUE;
    case 23:
    case "FACE_MONSTER":
      return Face.FACE_MONSTER;
    case 24:
    case "FACE_OLD":
      return Face.FACE_OLD;
    case 25:
    case "FACE_RAGE":
      return Face.FACE_RAGE;
    case 26:
    case "FACE_SERIOUS":
      return Face.FACE_SERIOUS;
    case 27:
    case "FACE_SMILE":
      return Face.FACE_SMILE;
    case 28:
    case "FACE_SMILE_LOL":
      return Face.FACE_SMILE_LOL;
    case 29:
    case "FACE_SMILE_TEETH":
      return Face.FACE_SMILE_TEETH;
    case 30:
    case "FACE_SMILE_WITH_MASK":
      return Face.FACE_SMILE_WITH_MASK;
    case 31:
    case "FACE_SOLEMN":
      return Face.FACE_SOLEMN;
    case 32:
    case "FACE_SUSPICIOUS":
      return Face.FACE_SUSPICIOUS;
    case 33:
    case "FACE_TIRED":
      return Face.FACE_TIRED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Face.UNRECOGNIZED;
  }
}

export function faceToJSON(object: Face): string {
  switch (object) {
    case Face.FACE_UNSPECIFIED:
      return "FACE_UNSPECIFIED";
    case Face.FACE_ANGRY:
      return "FACE_ANGRY";
    case Face.FACE_ANGRY_FANG:
      return "FACE_ANGRY_FANG";
    case Face.FACE_AWE:
      return "FACE_AWE";
    case Face.FACE_BIG_SMILE:
      return "FACE_BIG_SMILE";
    case Face.FACE_BLANK:
      return "FACE_BLANK";
    case Face.FACE_CALM:
      return "FACE_CALM";
    case Face.FACE_CALM_WITH_MASK:
      return "FACE_CALM_WITH_MASK";
    case Face.FACE_CHEEKY:
      return "FACE_CHEEKY";
    case Face.FACE_CHEERS_WITH_MASK:
      return "FACE_CHEERS_WITH_MASK";
    case Face.FACE_CONCERNED:
      return "FACE_CONCERNED";
    case Face.FACE_CONCERNED_FEAR:
      return "FACE_CONCERNED_FEAR";
    case Face.FACE_CONTEMPT:
      return "FACE_CONTEMPT";
    case Face.FACE_CUTE:
      return "FACE_CUTE";
    case Face.FACE_CYCLOPS:
      return "FACE_CYCLOPS";
    case Face.FACE_DRIVEN:
      return "FACE_DRIVEN";
    case Face.FACE_EATING_HAPPY:
      return "FACE_EATING_HAPPY";
    case Face.FACE_EXPLAINING:
      return "FACE_EXPLAINING";
    case Face.FACE_EYES_CLOSED:
      return "FACE_EYES_CLOSED";
    case Face.FACE_FEAR:
      return "FACE_FEAR";
    case Face.FACE_HECTIC:
      return "FACE_HECTIC";
    case Face.FACE_LOVE_GRIN_TEETH:
      return "FACE_LOVE_GRIN_TEETH";
    case Face.FACE_LOVE_GRIN_TONGUE:
      return "FACE_LOVE_GRIN_TONGUE";
    case Face.FACE_MONSTER:
      return "FACE_MONSTER";
    case Face.FACE_OLD:
      return "FACE_OLD";
    case Face.FACE_RAGE:
      return "FACE_RAGE";
    case Face.FACE_SERIOUS:
      return "FACE_SERIOUS";
    case Face.FACE_SMILE:
      return "FACE_SMILE";
    case Face.FACE_SMILE_LOL:
      return "FACE_SMILE_LOL";
    case Face.FACE_SMILE_TEETH:
      return "FACE_SMILE_TEETH";
    case Face.FACE_SMILE_WITH_MASK:
      return "FACE_SMILE_WITH_MASK";
    case Face.FACE_SOLEMN:
      return "FACE_SOLEMN";
    case Face.FACE_SUSPICIOUS:
      return "FACE_SUSPICIOUS";
    case Face.FACE_TIRED:
      return "FACE_TIRED";
    case Face.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Body {
  BODY_UNSPECIFIED = 0,
  BODY_BLAZER_BLACK_TEE = 1,
  BODY_BUTTON_POCKET_SHIRT = 2,
  BODY_BUTTON_SHIRT = 3,
  BODY_COFFEE = 4,
  BODY_COMPUTER = 5,
  BODY_DRESS = 6,
  BODY_EXPLAINING = 7,
  BODY_GAMING = 8,
  BODY_GYM_SHIRT = 9,
  BODY_HOODIE = 10,
  BODY_JACKET = 11,
  BODY_KILLER = 12,
  BODY_PAPER = 13,
  BODY_POINTING_UP = 14,
  BODY_POLKADOT_JACKET = 15,
  BODY_POLO_SWEATER = 16,
  BODY_SHIRT_COAT = 17,
  BODY_SPORTY_TEE = 18,
  BODY_STRIPED_TEE = 19,
  BODY_STRIPPED_POCKET_TEE = 20,
  BODY_SWEATER_DOTS = 21,
  BODY_TEE = 22,
  BODY_TEE_ARMS_CROSSED = 23,
  BODY_TEE_SELENA = 24,
  BODY_THUNDER_TEE = 25,
  BODY_TURTLENECK = 26,
  BODY_WHATEVER = 27,
  UNRECOGNIZED = -1,
}

export function bodyFromJSON(object: any): Body {
  switch (object) {
    case 0:
    case "BODY_UNSPECIFIED":
      return Body.BODY_UNSPECIFIED;
    case 1:
    case "BODY_BLAZER_BLACK_TEE":
      return Body.BODY_BLAZER_BLACK_TEE;
    case 2:
    case "BODY_BUTTON_POCKET_SHIRT":
      return Body.BODY_BUTTON_POCKET_SHIRT;
    case 3:
    case "BODY_BUTTON_SHIRT":
      return Body.BODY_BUTTON_SHIRT;
    case 4:
    case "BODY_COFFEE":
      return Body.BODY_COFFEE;
    case 5:
    case "BODY_COMPUTER":
      return Body.BODY_COMPUTER;
    case 6:
    case "BODY_DRESS":
      return Body.BODY_DRESS;
    case 7:
    case "BODY_EXPLAINING":
      return Body.BODY_EXPLAINING;
    case 8:
    case "BODY_GAMING":
      return Body.BODY_GAMING;
    case 9:
    case "BODY_GYM_SHIRT":
      return Body.BODY_GYM_SHIRT;
    case 10:
    case "BODY_HOODIE":
      return Body.BODY_HOODIE;
    case 11:
    case "BODY_JACKET":
      return Body.BODY_JACKET;
    case 12:
    case "BODY_KILLER":
      return Body.BODY_KILLER;
    case 13:
    case "BODY_PAPER":
      return Body.BODY_PAPER;
    case 14:
    case "BODY_POINTING_UP":
      return Body.BODY_POINTING_UP;
    case 15:
    case "BODY_POLKADOT_JACKET":
      return Body.BODY_POLKADOT_JACKET;
    case 16:
    case "BODY_POLO_SWEATER":
      return Body.BODY_POLO_SWEATER;
    case 17:
    case "BODY_SHIRT_COAT":
      return Body.BODY_SHIRT_COAT;
    case 18:
    case "BODY_SPORTY_TEE":
      return Body.BODY_SPORTY_TEE;
    case 19:
    case "BODY_STRIPED_TEE":
      return Body.BODY_STRIPED_TEE;
    case 20:
    case "BODY_STRIPPED_POCKET_TEE":
      return Body.BODY_STRIPPED_POCKET_TEE;
    case 21:
    case "BODY_SWEATER_DOTS":
      return Body.BODY_SWEATER_DOTS;
    case 22:
    case "BODY_TEE":
      return Body.BODY_TEE;
    case 23:
    case "BODY_TEE_ARMS_CROSSED":
      return Body.BODY_TEE_ARMS_CROSSED;
    case 24:
    case "BODY_TEE_SELENA":
      return Body.BODY_TEE_SELENA;
    case 25:
    case "BODY_THUNDER_TEE":
      return Body.BODY_THUNDER_TEE;
    case 26:
    case "BODY_TURTLENECK":
      return Body.BODY_TURTLENECK;
    case 27:
    case "BODY_WHATEVER":
      return Body.BODY_WHATEVER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Body.UNRECOGNIZED;
  }
}

export function bodyToJSON(object: Body): string {
  switch (object) {
    case Body.BODY_UNSPECIFIED:
      return "BODY_UNSPECIFIED";
    case Body.BODY_BLAZER_BLACK_TEE:
      return "BODY_BLAZER_BLACK_TEE";
    case Body.BODY_BUTTON_POCKET_SHIRT:
      return "BODY_BUTTON_POCKET_SHIRT";
    case Body.BODY_BUTTON_SHIRT:
      return "BODY_BUTTON_SHIRT";
    case Body.BODY_COFFEE:
      return "BODY_COFFEE";
    case Body.BODY_COMPUTER:
      return "BODY_COMPUTER";
    case Body.BODY_DRESS:
      return "BODY_DRESS";
    case Body.BODY_EXPLAINING:
      return "BODY_EXPLAINING";
    case Body.BODY_GAMING:
      return "BODY_GAMING";
    case Body.BODY_GYM_SHIRT:
      return "BODY_GYM_SHIRT";
    case Body.BODY_HOODIE:
      return "BODY_HOODIE";
    case Body.BODY_JACKET:
      return "BODY_JACKET";
    case Body.BODY_KILLER:
      return "BODY_KILLER";
    case Body.BODY_PAPER:
      return "BODY_PAPER";
    case Body.BODY_POINTING_UP:
      return "BODY_POINTING_UP";
    case Body.BODY_POLKADOT_JACKET:
      return "BODY_POLKADOT_JACKET";
    case Body.BODY_POLO_SWEATER:
      return "BODY_POLO_SWEATER";
    case Body.BODY_SHIRT_COAT:
      return "BODY_SHIRT_COAT";
    case Body.BODY_SPORTY_TEE:
      return "BODY_SPORTY_TEE";
    case Body.BODY_STRIPED_TEE:
      return "BODY_STRIPED_TEE";
    case Body.BODY_STRIPPED_POCKET_TEE:
      return "BODY_STRIPPED_POCKET_TEE";
    case Body.BODY_SWEATER_DOTS:
      return "BODY_SWEATER_DOTS";
    case Body.BODY_TEE:
      return "BODY_TEE";
    case Body.BODY_TEE_ARMS_CROSSED:
      return "BODY_TEE_ARMS_CROSSED";
    case Body.BODY_TEE_SELENA:
      return "BODY_TEE_SELENA";
    case Body.BODY_THUNDER_TEE:
      return "BODY_THUNDER_TEE";
    case Body.BODY_TURTLENECK:
      return "BODY_TURTLENECK";
    case Body.BODY_WHATEVER:
      return "BODY_WHATEVER";
    case Body.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum FacialHair {
  FACIAL_HAIR_NONE = 0,
  FACIAL_HAIR_CHIN = 1,
  FACIAL_HAIR_FULL = 2,
  FACIAL_HAIR_FULL_COLOR = 3,
  FACIAL_HAIR_FULL_MAX = 4,
  FACIAL_HAIR_FULL_MEDIUM = 5,
  FACIAL_HAIR_GOATEE = 6,
  FACIAL_HAIR_GOATEE_FULL = 7,
  FACIAL_HAIR_MUSTACHE_BULL = 8,
  FACIAL_HAIR_MUSTACHE_EIGHT = 9,
  FACIAL_HAIR_MUSTACHE_FIVE = 10,
  FACIAL_HAIR_MUSTACHE_NINE = 11,
  FACIAL_HAIR_MUSTACHE_SEVEN = 12,
  FACIAL_HAIR_MUSTACHE_SIX = 13,
  FACIAL_HAIR_MUSTACHE_THIN = 14,
  FACIAL_HAIR_MUSTACHE_THIN_BULL = 15,
  FACIAL_HAIR_MUSTACHE_YOSEMITE = 16,
  UNRECOGNIZED = -1,
}

export function facialHairFromJSON(object: any): FacialHair {
  switch (object) {
    case 0:
    case "FACIAL_HAIR_NONE":
      return FacialHair.FACIAL_HAIR_NONE;
    case 1:
    case "FACIAL_HAIR_CHIN":
      return FacialHair.FACIAL_HAIR_CHIN;
    case 2:
    case "FACIAL_HAIR_FULL":
      return FacialHair.FACIAL_HAIR_FULL;
    case 3:
    case "FACIAL_HAIR_FULL_COLOR":
      return FacialHair.FACIAL_HAIR_FULL_COLOR;
    case 4:
    case "FACIAL_HAIR_FULL_MAX":
      return FacialHair.FACIAL_HAIR_FULL_MAX;
    case 5:
    case "FACIAL_HAIR_FULL_MEDIUM":
      return FacialHair.FACIAL_HAIR_FULL_MEDIUM;
    case 6:
    case "FACIAL_HAIR_GOATEE":
      return FacialHair.FACIAL_HAIR_GOATEE;
    case 7:
    case "FACIAL_HAIR_GOATEE_FULL":
      return FacialHair.FACIAL_HAIR_GOATEE_FULL;
    case 8:
    case "FACIAL_HAIR_MUSTACHE_BULL":
      return FacialHair.FACIAL_HAIR_MUSTACHE_BULL;
    case 9:
    case "FACIAL_HAIR_MUSTACHE_EIGHT":
      return FacialHair.FACIAL_HAIR_MUSTACHE_EIGHT;
    case 10:
    case "FACIAL_HAIR_MUSTACHE_FIVE":
      return FacialHair.FACIAL_HAIR_MUSTACHE_FIVE;
    case 11:
    case "FACIAL_HAIR_MUSTACHE_NINE":
      return FacialHair.FACIAL_HAIR_MUSTACHE_NINE;
    case 12:
    case "FACIAL_HAIR_MUSTACHE_SEVEN":
      return FacialHair.FACIAL_HAIR_MUSTACHE_SEVEN;
    case 13:
    case "FACIAL_HAIR_MUSTACHE_SIX":
      return FacialHair.FACIAL_HAIR_MUSTACHE_SIX;
    case 14:
    case "FACIAL_HAIR_MUSTACHE_THIN":
      return FacialHair.FACIAL_HAIR_MUSTACHE_THIN;
    case 15:
    case "FACIAL_HAIR_MUSTACHE_THIN_BULL":
      return FacialHair.FACIAL_HAIR_MUSTACHE_THIN_BULL;
    case 16:
    case "FACIAL_HAIR_MUSTACHE_YOSEMITE":
      return FacialHair.FACIAL_HAIR_MUSTACHE_YOSEMITE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FacialHair.UNRECOGNIZED;
  }
}

export function facialHairToJSON(object: FacialHair): string {
  switch (object) {
    case FacialHair.FACIAL_HAIR_NONE:
      return "FACIAL_HAIR_NONE";
    case FacialHair.FACIAL_HAIR_CHIN:
      return "FACIAL_HAIR_CHIN";
    case FacialHair.FACIAL_HAIR_FULL:
      return "FACIAL_HAIR_FULL";
    case FacialHair.FACIAL_HAIR_FULL_COLOR:
      return "FACIAL_HAIR_FULL_COLOR";
    case FacialHair.FACIAL_HAIR_FULL_MAX:
      return "FACIAL_HAIR_FULL_MAX";
    case FacialHair.FACIAL_HAIR_FULL_MEDIUM:
      return "FACIAL_HAIR_FULL_MEDIUM";
    case FacialHair.FACIAL_HAIR_GOATEE:
      return "FACIAL_HAIR_GOATEE";
    case FacialHair.FACIAL_HAIR_GOATEE_FULL:
      return "FACIAL_HAIR_GOATEE_FULL";
    case FacialHair.FACIAL_HAIR_MUSTACHE_BULL:
      return "FACIAL_HAIR_MUSTACHE_BULL";
    case FacialHair.FACIAL_HAIR_MUSTACHE_EIGHT:
      return "FACIAL_HAIR_MUSTACHE_EIGHT";
    case FacialHair.FACIAL_HAIR_MUSTACHE_FIVE:
      return "FACIAL_HAIR_MUSTACHE_FIVE";
    case FacialHair.FACIAL_HAIR_MUSTACHE_NINE:
      return "FACIAL_HAIR_MUSTACHE_NINE";
    case FacialHair.FACIAL_HAIR_MUSTACHE_SEVEN:
      return "FACIAL_HAIR_MUSTACHE_SEVEN";
    case FacialHair.FACIAL_HAIR_MUSTACHE_SIX:
      return "FACIAL_HAIR_MUSTACHE_SIX";
    case FacialHair.FACIAL_HAIR_MUSTACHE_THIN:
      return "FACIAL_HAIR_MUSTACHE_THIN";
    case FacialHair.FACIAL_HAIR_MUSTACHE_THIN_BULL:
      return "FACIAL_HAIR_MUSTACHE_THIN_BULL";
    case FacialHair.FACIAL_HAIR_MUSTACHE_YOSEMITE:
      return "FACIAL_HAIR_MUSTACHE_YOSEMITE";
    case FacialHair.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Accessory {
  ACCESSORY_NONE = 0,
  ACCESSORY_EYEPATCH = 1,
  ACCESSORY_GLASSES = 2,
  ACCESSORY_GLASSES_FIVE = 3,
  ACCESSORY_GLASSES_FOUR = 4,
  ACCESSORY_GLASSES_SIX = 5,
  ACCESSORY_GLASSES_THREE = 6,
  ACCESSORY_GLASSES_TWO = 7,
  ACCESSORY_SUNGLASSES = 8,
  ACCESSORY_SUNGLASSES_TWO = 9,
  UNRECOGNIZED = -1,
}

export function accessoryFromJSON(object: any): Accessory {
  switch (object) {
    case 0:
    case "ACCESSORY_NONE":
      return Accessory.ACCESSORY_NONE;
    case 1:
    case "ACCESSORY_EYEPATCH":
      return Accessory.ACCESSORY_EYEPATCH;
    case 2:
    case "ACCESSORY_GLASSES":
      return Accessory.ACCESSORY_GLASSES;
    case 3:
    case "ACCESSORY_GLASSES_FIVE":
      return Accessory.ACCESSORY_GLASSES_FIVE;
    case 4:
    case "ACCESSORY_GLASSES_FOUR":
      return Accessory.ACCESSORY_GLASSES_FOUR;
    case 5:
    case "ACCESSORY_GLASSES_SIX":
      return Accessory.ACCESSORY_GLASSES_SIX;
    case 6:
    case "ACCESSORY_GLASSES_THREE":
      return Accessory.ACCESSORY_GLASSES_THREE;
    case 7:
    case "ACCESSORY_GLASSES_TWO":
      return Accessory.ACCESSORY_GLASSES_TWO;
    case 8:
    case "ACCESSORY_SUNGLASSES":
      return Accessory.ACCESSORY_SUNGLASSES;
    case 9:
    case "ACCESSORY_SUNGLASSES_TWO":
      return Accessory.ACCESSORY_SUNGLASSES_TWO;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Accessory.UNRECOGNIZED;
  }
}

export function accessoryToJSON(object: Accessory): string {
  switch (object) {
    case Accessory.ACCESSORY_NONE:
      return "ACCESSORY_NONE";
    case Accessory.ACCESSORY_EYEPATCH:
      return "ACCESSORY_EYEPATCH";
    case Accessory.ACCESSORY_GLASSES:
      return "ACCESSORY_GLASSES";
    case Accessory.ACCESSORY_GLASSES_FIVE:
      return "ACCESSORY_GLASSES_FIVE";
    case Accessory.ACCESSORY_GLASSES_FOUR:
      return "ACCESSORY_GLASSES_FOUR";
    case Accessory.ACCESSORY_GLASSES_SIX:
      return "ACCESSORY_GLASSES_SIX";
    case Accessory.ACCESSORY_GLASSES_THREE:
      return "ACCESSORY_GLASSES_THREE";
    case Accessory.ACCESSORY_GLASSES_TWO:
      return "ACCESSORY_GLASSES_TWO";
    case Accessory.ACCESSORY_SUNGLASSES:
      return "ACCESSORY_SUNGLASSES";
    case Accessory.ACCESSORY_SUNGLASSES_TWO:
      return "ACCESSORY_SUNGLASSES_TWO";
    case Accessory.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface AvatarConfig {
  head: Head;
  body: Body;
  face: Face;
  facialHair: FacialHair;
  accessory: Accessory;
  /** Colors — only included when overriding defaults */
  skinColor?: string | undefined;
  outlineColor?: string | undefined;
  topColor?: string | undefined;
  jacketColor?: string | undefined;
  hairColor?: string | undefined;
  hatColor?: string | undefined;
  beardColor?: string | undefined;
  accessoryColor?: string | undefined;
  propColor?: string | undefined;
  backgroundColor?: string | undefined;
}

function createBaseAvatarConfig(): AvatarConfig {
  return {
    head: 0,
    body: 0,
    face: 0,
    facialHair: 0,
    accessory: 0,
    skinColor: undefined,
    outlineColor: undefined,
    topColor: undefined,
    jacketColor: undefined,
    hairColor: undefined,
    hatColor: undefined,
    beardColor: undefined,
    accessoryColor: undefined,
    propColor: undefined,
    backgroundColor: undefined,
  };
}

export const AvatarConfig: MessageFns<AvatarConfig> = {
  encode(message: AvatarConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.head !== 0) {
      writer.uint32(8).int32(message.head);
    }
    if (message.body !== 0) {
      writer.uint32(16).int32(message.body);
    }
    if (message.face !== 0) {
      writer.uint32(24).int32(message.face);
    }
    if (message.facialHair !== 0) {
      writer.uint32(32).int32(message.facialHair);
    }
    if (message.accessory !== 0) {
      writer.uint32(40).int32(message.accessory);
    }
    if (message.skinColor !== undefined) {
      writer.uint32(82).string(message.skinColor);
    }
    if (message.outlineColor !== undefined) {
      writer.uint32(90).string(message.outlineColor);
    }
    if (message.topColor !== undefined) {
      writer.uint32(98).string(message.topColor);
    }
    if (message.jacketColor !== undefined) {
      writer.uint32(106).string(message.jacketColor);
    }
    if (message.hairColor !== undefined) {
      writer.uint32(114).string(message.hairColor);
    }
    if (message.hatColor !== undefined) {
      writer.uint32(122).string(message.hatColor);
    }
    if (message.beardColor !== undefined) {
      writer.uint32(130).string(message.beardColor);
    }
    if (message.accessoryColor !== undefined) {
      writer.uint32(138).string(message.accessoryColor);
    }
    if (message.propColor !== undefined) {
      writer.uint32(146).string(message.propColor);
    }
    if (message.backgroundColor !== undefined) {
      writer.uint32(154).string(message.backgroundColor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AvatarConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAvatarConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.head = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.body = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.face = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.facialHair = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.accessory = reader.int32() as any;
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.skinColor = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.outlineColor = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.topColor = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.jacketColor = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.hairColor = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.hatColor = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.beardColor = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.accessoryColor = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.propColor = reader.string();
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.backgroundColor = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AvatarConfig {
    return {
      head: isSet(object.head) ? headFromJSON(object.head) : 0,
      body: isSet(object.body) ? bodyFromJSON(object.body) : 0,
      face: isSet(object.face) ? faceFromJSON(object.face) : 0,
      facialHair: isSet(object.facialHair)
        ? facialHairFromJSON(object.facialHair)
        : isSet(object.facial_hair)
        ? facialHairFromJSON(object.facial_hair)
        : 0,
      accessory: isSet(object.accessory) ? accessoryFromJSON(object.accessory) : 0,
      skinColor: isSet(object.skinColor)
        ? globalThis.String(object.skinColor)
        : isSet(object.skin_color)
        ? globalThis.String(object.skin_color)
        : undefined,
      outlineColor: isSet(object.outlineColor)
        ? globalThis.String(object.outlineColor)
        : isSet(object.outline_color)
        ? globalThis.String(object.outline_color)
        : undefined,
      topColor: isSet(object.topColor)
        ? globalThis.String(object.topColor)
        : isSet(object.top_color)
        ? globalThis.String(object.top_color)
        : undefined,
      jacketColor: isSet(object.jacketColor)
        ? globalThis.String(object.jacketColor)
        : isSet(object.jacket_color)
        ? globalThis.String(object.jacket_color)
        : undefined,
      hairColor: isSet(object.hairColor)
        ? globalThis.String(object.hairColor)
        : isSet(object.hair_color)
        ? globalThis.String(object.hair_color)
        : undefined,
      hatColor: isSet(object.hatColor)
        ? globalThis.String(object.hatColor)
        : isSet(object.hat_color)
        ? globalThis.String(object.hat_color)
        : undefined,
      beardColor: isSet(object.beardColor)
        ? globalThis.String(object.beardColor)
        : isSet(object.beard_color)
        ? globalThis.String(object.beard_color)
        : undefined,
      accessoryColor: isSet(object.accessoryColor)
        ? globalThis.String(object.accessoryColor)
        : isSet(object.accessory_color)
        ? globalThis.String(object.accessory_color)
        : undefined,
      propColor: isSet(object.propColor)
        ? globalThis.String(object.propColor)
        : isSet(object.prop_color)
        ? globalThis.String(object.prop_color)
        : undefined,
      backgroundColor: isSet(object.backgroundColor)
        ? globalThis.String(object.backgroundColor)
        : isSet(object.background_color)
        ? globalThis.String(object.background_color)
        : undefined,
    };
  },

  toJSON(message: AvatarConfig): unknown {
    const obj: any = {};
    if (message.head !== 0) {
      obj.head = headToJSON(message.head);
    }
    if (message.body !== 0) {
      obj.body = bodyToJSON(message.body);
    }
    if (message.face !== 0) {
      obj.face = faceToJSON(message.face);
    }
    if (message.facialHair !== 0) {
      obj.facialHair = facialHairToJSON(message.facialHair);
    }
    if (message.accessory !== 0) {
      obj.accessory = accessoryToJSON(message.accessory);
    }
    if (message.skinColor !== undefined) {
      obj.skinColor = message.skinColor;
    }
    if (message.outlineColor !== undefined) {
      obj.outlineColor = message.outlineColor;
    }
    if (message.topColor !== undefined) {
      obj.topColor = message.topColor;
    }
    if (message.jacketColor !== undefined) {
      obj.jacketColor = message.jacketColor;
    }
    if (message.hairColor !== undefined) {
      obj.hairColor = message.hairColor;
    }
    if (message.hatColor !== undefined) {
      obj.hatColor = message.hatColor;
    }
    if (message.beardColor !== undefined) {
      obj.beardColor = message.beardColor;
    }
    if (message.accessoryColor !== undefined) {
      obj.accessoryColor = message.accessoryColor;
    }
    if (message.propColor !== undefined) {
      obj.propColor = message.propColor;
    }
    if (message.backgroundColor !== undefined) {
      obj.backgroundColor = message.backgroundColor;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AvatarConfig>, I>>(base?: I): AvatarConfig {
    return AvatarConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AvatarConfig>, I>>(object: I): AvatarConfig {
    const message = createBaseAvatarConfig();
    message.head = object.head ?? 0;
    message.body = object.body ?? 0;
    message.face = object.face ?? 0;
    message.facialHair = object.facialHair ?? 0;
    message.accessory = object.accessory ?? 0;
    message.skinColor = object.skinColor ?? undefined;
    message.outlineColor = object.outlineColor ?? undefined;
    message.topColor = object.topColor ?? undefined;
    message.jacketColor = object.jacketColor ?? undefined;
    message.hairColor = object.hairColor ?? undefined;
    message.hatColor = object.hatColor ?? undefined;
    message.beardColor = object.beardColor ?? undefined;
    message.accessoryColor = object.accessoryColor ?? undefined;
    message.propColor = object.propColor ?? undefined;
    message.backgroundColor = object.backgroundColor ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
